[package]
name = "rigid-body-physics-engine"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["-C target-cpu=native"]

[dependencies]
gxhash = "3.4.1"
sdl2 = { version = "0.37.0", default-features = false }
